[package]
name = "duplicati_proxy"
version = "0.1.0"
authors = ["Hand-of-Cthulhu <3rdhandofcthulhu@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
serde="*"
serde_derive="*"
lazy_static = "*"
zip = "*"
walkdir="*"
diesel = { version = "*", features = ["mysql"] }
base64 = "*"
ring = "0.11.0"
#serde_json = "*"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates", "json"]